# Generated by Django 3.2.7 on 2021-09-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=15)),
                ('cpassword', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=350)),
            ],
        ),
    ]
