# Generated by Django 3.2.7 on 2021-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20210921_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='cpassword',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
